version: "2"
services:
  editorapi:
    image: registry.jorgeadolfo.com/epav-sugar-syntax-api:latest
    #ports:
    #  - 5000:5000
  editorgui:
    image: registry.jorgeadolfo.com/epav-sugar-syntax-gui:latest
    ports:
      - 8080:8080
    links:
      - editorapi
