FROM registry.jorgeadolfo.com/epav-api:latest

RUN apt-get update && apt-get install -y unzip

RUN mkdir /sugar-api
WORKDIR /sugar-api

RUN pip install -U flask-cors

COPY server .

CMD ["python", "server"]
